### ISSUE TITLE
I can't build with Visual Studio 2017 to start contributing!

### ISSUE THREAD

**Issue by iamanas20** [theweavrs/BreadPlayer#200]
#### What Happened?
_I was following your guidelines on how to contribute, and when I want to build it says that pretty much every namespace is not defined or imported:
![image](https://user-images.githubusercontent.com/27561160/32232995-3f37827c-be51-11e7-8581-e9699989d589.png)

#### How it happened?
_I have no idea_

#### What were you expecting?
_To work smoothly, and start contributing_

### Additional Comments:
_How to solve this issue_

**Comment by theweavrs** [comment]
Can you please tell me:
1. The version of Windows 10 SDK
2. The version of Visual Studio 2017 (Go to Help > About Microsoft Visual Studio)
3. The version of .NET Core?

As a hit and trial: can you this:
1. Unload the project and reload it.
2. Try restoring nuget by Right Clicking on the .sln in the Solution Explorer and pressing "Restore Nuget Packages".

Thanks, hope this helps.

**Comment by iamanas20** [comment]
I restored nuget packages, and most of the errors are gone, only one's left I have no idea what is it!
![image](https://user-images.githubusercontent.com/27561160/32240317-f1013026-be64-11e7-99ba-86e75a09aeb1.png)


1. Windows 10 SDK for Fall Creators Update (10.0.16299.15
2. Visual Studio 2017 version 15.5.0 preview 1
3. .NET CORE 2.0

**Comment by theweavrs** [comment]
Your version are all good (better than mine 😆 ). That error is about the project BreadPlayer.Controls. Try building it separately.

**Comment by iamanas20** [comment]
for some reason the BreadPlayer.Controls does load. I open the output window and this is what's been shown:
![image](https://user-images.githubusercontent.com/27561160/32242482-da4b5ea0-be6a-11e7-9378-79420c008e5d.png)

🤔

**Comment by theweavrs** [comment]
I think the BreadPlayer.Controls project is targeting an old version of Windows 10 SDK which you do not have. Simply do this:

Open the .csproj file in a Text Editor.
Find and replace these two lines:
```xml
    <TargetPlatformVersion>10.0.14393.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.10240.0</TargetPlatformMinVersion>
```
With these:
```
    <TargetPlatformVersion>10.0.16299.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.14393.0</TargetPlatformMinVersion>
```

**Comment by iamanas20** [comment]
I got it to work, thanks man, looking forward to be a great contributor to you! any tips, guidelines or a checklist of the features you guys are working on or you wanna add, just briefly right here!

**Comment by theweavrs** [comment]
@iamanas20 That's good news! Congrats. 👏 The one feature that I cannot implement but really need it is XBox One support. If you happen to have that, that would be a **tremendous** contribution.

Anyhow, since there is a less chance of the above, here's a small list of things you can do:
1. Currently I am working on Folder Navigation and have nearly completed the basics of it. You can help me with that.
2. Go to this [issue](https://github.com/theweavrs/BreadPlayer/issues/17) and you will find a list of all the things people have requested. You can choose any one from the list and begin development.
3. One other thing that would be welcome and appreciated is DLNA support. In UWP, its rather easy and if you want to work on that, you are welcome to.

All else is really up to you. I don't enforce any hard rules on contributors regarding contributions but you can read [this](https://github.com/theweavrs/BreadPlayer/blob/master/CONTRIBUTING.md).

And at last, welcome to Bread it is good to have you!

**Comment by theweavrs** [comment]
Closing as the issue seems fixed.
