### ISSUE TITLE
Not all songs being loaded.

### ISSUE THREAD

**Issue by theweavrs** [theweavrs/BreadPlayer#28]
**What happens:** If you load 1000 songs, some songs are not loaded.

**What should happen:** All songs should load into library.

_Remarks: I think this is a problem with file access permissions but I could be wrong._

@DannyTalent @Bond-009 Can you please try and reproduce this?

**Comment by DannyTalent** [comment]
I'm not sure how I'm going to count 1000 songs!

I did however find that it only detected (and loaded) 1327 out of 1449 songs, but I think that may be because it doesn't open all filetypes? This is my library, according to foobar2000: 

> Codec profile : MP3 CBR (85.5%); WMA V2 (3.2%); MP3 VBR V2 (2.9%); MP3 VBR V0 (2.7%); AAC LC (2.6%); FLAC (1.0%); ALAC (0.7%); MP3 ABR (0.5%); MP3 VBR (0.4%); MP3 (0.2%); MP3 VBR V5 (0.2%)

Does bread player support FLAC / AAC / ALAC / WMA? Because if it doesn't then those numbers'd make sense.
After playing one song, the app hanged for a while and the status bar now says "Access denied. (Excep_FromHResult 0x80070005)"

**Comment by theweavrs** [comment]
@DannyTalent BreadPlayer does support all those formats but they were not added to the filters while library loading. Did that now so this must be fixed.

**Comment by theweavrs** [comment]
@DannyTalent Try it out on the latest version.

**Comment by DannyTalent** [comment]
I reinstalled to make sure, since at first it only found 1327 again... And yes, it did get 1435 songs (in an impressive 63 seconds I must add, for an uwa). I get 1449 on AIMP just because one file has a .cue that splits it in 15 (including itself so.. 1449-14)

**Comment by theweavrs** [comment]
@DannyTalent So the issue is fixed! Anyways, I tested on an i7 and got 1119 song in 12-21 seconds (with and without albumarts). What hardware did you test on?

**Comment by DannyTalent** [comment]
FX-6300, also traditional mechanical HDD... Most songs have album arts

**Comment by theweavrs** [comment]
My collection had 515 album arts but I guess I had the advantage of songs being saved in memory (I test with these a lot.) so overall good results but can be made better. 63 seconds are too long for big libraries. Imagine 10,000 songs...haha!
