### ISSUE TITLE
Instant crash

### ISSUE THREAD

**Issue by Bond-009** [theweavrs/BreadPlayer#68]
If I build from source it crashes.
Ex: Unhandled exception at 0x06217CE8 (Windows.UI.Xaml.dll) in BreadPlayer.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x157DCCE8, 0x00000006). occurred
Ex2: An exception of type 'System.Exception' occurred in System.Private.CoreLib.dll but was not handled in user code
Unspecified error (Excep_FromHResult 0x80004005) occurred

**Comment by hildebrandt87** [comment]
I could not reproduce it so far. 
Have you tried to start a fresh sourcecode download ?

**Comment by Bond-009** [comment]
Yes, I did

**Comment by theweavrs** [comment]
@Bond-009 @hildebrandt87  This is a PC specific issue, I think. Perhaps, the app is having problems accessing the Music Library. I can't be sure until I reproduce this again.

@Bond-009 Remove the `try/catch` and try reproducing again with breakpoints in the `AutoLoadMusicLibrary` method and see on which line the bug is present. Furthermore, also trying breakpoints with `AddFolderToLibraryAsync` method because that is what's being called. See if the songs are present in the `IReadOnlyList<StorageFile> files` and also the `count` variable.

**Comment by Bond-009** [comment]
I think this is the line that causes the crash 
![devenv_2016-12-09_18-05-49](https://cloud.githubusercontent.com/assets/21289123/21057490/307f7c3e-be3a-11e6-85b4-22be3b82795b.png)

**Comment by theweavrs** [comment]
@Bond-009 See the `files` variable in the `Locals` Window. Check if there are any files in it; it's a list.

**Comment by Bond-009** [comment]
![2016-12-22_14-28-44](https://cloud.githubusercontent.com/assets/21289123/21427159/25eedc10-c853-11e6-8516-b9276ca2b03d.png)

**Comment by Bond-009** [comment]
Closing this, it doesn't crash anymore
